-- move_data.sql
-- Move incremental data from Account_Raw to Omega table

MERGE INTO SNOW_GIT_DB.SNOW_GIT_SCHEMA.OMEGA t
USING SNOW_GIT_DB.SNOW_GIT_SCHEMA.ACCOUNT_RAW s
ON t.ACCOUNT_ID = s.ACCOUNT_ID

WHEN MATCHED AND (
    t.ACCOUNT_NAME <> s.ACCOUNT_NAME
    OR t.ACCOUNT_STATUS <> s.ACCOUNT_STATUS
    OR t.UPDATED_AT <> s.UPDATED_AT
)
THEN UPDATE SET
    t.ACCOUNT_NAME = s.ACCOUNT_NAME,
    t.ACCOUNT_STATUS = s.ACCOUNT_STATUS,
    t.UPDATED_AT = s.UPDATED_AT

WHEN NOT MATCHED THEN
  INSERT (ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_STATUS, CREATED_AT, UPDATED_AT)
  VALUES (s.ACCOUNT_ID, s.ACCOUNT_NAME, s.ACCOUNT_STATUS, s.CREATED_AT, s.UPDATED_AT);
