-- move_data.sql
-- Move incremental data from ACCOUNT_RAW to OMEGA table

MERGE INTO SNOW_GIT_DB.SNOW_GIT_SCHEMA.OMEGA t
USING SNOW_GIT_DB.SNOW_GIT_SCHEMA.ACCOUNT_RAW s
ON t.ACCOUNT_ID = s.ACCOUNT_ID

WHEN MATCHED AND (
    t.NAME <> s.NAME
    OR t.BALANCE <> s.BALANCE
    OR t.UPDATED_AT <> s.UPDATED_AT
)
THEN UPDATE SET
    t.NAME = s.NAME,
    t.BALANCE = s.BALANCE,
    t.UPDATED_AT = s.UPDATED_AT,
    t.data_hash = MD5(NVL(TO_VARCHAR(s.NAME), '') || '|' || NVL(TO_VARCHAR(s.BALANCE), '') || '|' || NVL(TO_VARCHAR(s.UPDATED_AT), ''))

WHEN NOT MATCHED THEN
  INSERT (ACCOUNT_ID, NAME, BALANCE, UPDATED_AT, data_hash)
  VALUES (
    s.ACCOUNT_ID,
    s.NAME,
    s.BALANCE,
    s.UPDATED_AT,
    MD5(NVL(TO_VARCHAR(s.NAME), '') || '|' || NVL(TO_VARCHAR(s.BALANCE), '') || '|' || NVL(TO_VARCHAR(s.UPDATED_AT), ''))
  );
