-- move_data.sql
USE SCHEMA PUBLIC;

-- 1️⃣ Merge new or updated records from ACCOUNT_RAW → OMEGA
MERGE INTO OMEGA AS TARGET
USING ACCOUNT_RAW AS SOURCE
ON TARGET.ACCOUNT_ID = SOURCE.ACCOUNT_ID
WHEN MATCHED AND (
      TARGET.NAME != SOURCE.NAME 
   OR TARGET.BALANCE != SOURCE.BALANCE
   OR TARGET.UPDATED_AT != SOURCE.UPDATED_AT
)
THEN UPDATE SET
  NAME = SOURCE.NAME,
  BALANCE = SOURCE.BALANCE,
  UPDATED_AT = SOURCE.UPDATED_AT
WHEN NOT MATCHED THEN
  INSERT (ACCOUNT_ID, NAME, BALANCE, UPDATED_AT)
  VALUES (SOURCE.ACCOUNT_ID, SOURCE.NAME, SOURCE.BALANCE, SOURCE.UPDATED_AT);
